# Generated by Django 4.2.7 on 2025-08-13 10:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_redflag_recommendation_redflag_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField()),
                ('answer_type', models.CharField(choices=[('generated', 'Generated'), ('extracted', 'Extracted')], default='generated', max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('relevance_score', models.FloatField(default=0.0)),
                ('source_chunks', models.JSONField(default=list, help_text='List of source chunk IDs')),
                ('source_pages', models.JSONField(default=list, help_text='List of source page numbers')),
                ('generation_time', models.FloatField(default=0.0)),
                ('model_used', models.CharField(default='sentence-transformers', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_answers', to='main.question')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('citation_text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('relevance_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='main.answer')),
                ('source_chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='main.documentchunk')),
            ],
            options={
                'verbose_name': 'Citation',
                'verbose_name_plural': 'Citations',
                'ordering': ['-relevance_score', 'page_number'],
            },
        ),
    ]
