# Generated by Django 4.2.7 on 2025-08-13 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_answer_citation'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='grounded',
            field=models.BooleanField(default=False, help_text='Whether answer is grounded in document content'),
        ),
        migrations.AddField(
            model_name='question',
            name='complexity_level',
            field=models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex')], default='medium', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='key_terms',
            field=models.JSONField(default=list, help_text='Extracted key terms from question'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('factual', 'Factual'), ('comparison', 'Comparison'), ('procedural', 'Procedural'), ('interpretation', 'Interpretation'), ('yes_no', 'Yes/No'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
    ]
