# Generated by Django 4.2.7 on 2025-08-13 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='documents',
        ),
        migrations.AddField(
            model_name='document',
            name='user_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.usersession'),
        ),
    ]
