# Generated by Django 4.2.7 on 2025-08-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20250813_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='complexity_level',
            field=models.CharField(default='medium', help_text='Document complexity', max_length=20),
        ),
        migrations.AddField(
            model_name='analysis',
            name='extraction_method',
            field=models.CharField(blank=True, help_text='OCR or direct extraction', max_length=50),
        ),
        migrations.AddField(
            model_name='analysis',
            name='legal_terms_found',
            field=models.TextField(blank=True, help_text='Comma-separated legal terms'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='processing_notes',
            field=models.TextField(blank=True, help_text='Processing notes and summary'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='summary',
            field=models.TextField(blank=True, help_text='Analysis summary'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_sentences',
            field=models.IntegerField(default=0, help_text='Total sentences in document'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_words',
            field=models.IntegerField(default=0, help_text='Total words in document'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='analysis_type',
            field=models.CharField(choices=[('summary', 'Summary'), ('clauses', 'Clauses'), ('red_flags', 'Red Flags'), ('qa', 'Q&A')], default='summary', max_length=20),
        ),
    ]
