# Generated by Django 4.2.7 on 2025-08-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_analysis_complexity_level_analysis_extraction_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redflag',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='redflag',
            name='category',
            field=models.CharField(choices=[('financial', 'Financial'), ('legal', 'Legal'), ('operational', 'Operational'), ('compliance', 'Compliance'), ('reputational', 'Reputational'), ('strategic', 'Strategic')], default='legal', max_length=20),
        ),
        migrations.AddField(
            model_name='redflag',
            name='recommendations',
            field=models.JSONField(default=list, help_text='List of recommended actions'),
        ),
        migrations.AlterField(
            model_name='clause',
            name='clause_type',
            field=models.CharField(choices=[('termination', 'Termination'), ('auto_renewal', 'Auto-renewal'), ('penalties', 'Penalties'), ('confidentiality', 'Confidentiality'), ('liability', 'Liability'), ('jurisdiction', 'Jurisdiction'), ('arbitration', 'Arbitration'), ('force_majeure', 'Force Majeure'), ('indemnification', 'Indemnification'), ('non_compete', 'Non-Compete'), ('severability', 'Severability'), ('entire_agreement', 'Entire Agreement'), ('amendment', 'Amendment'), ('assignment', 'Assignment'), ('notice', 'Notice'), ('governing_law', 'Governing Law'), ('other', 'Other')], max_length=20),
        ),
    ]
